// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// paircountxx
List paircountxx(NumericMatrix x, double dr, double rmax);
RcppExport SEXP _cooltools_paircountxx(SEXP xSEXP, SEXP drSEXP, SEXP rmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type dr(drSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(paircountxx(x, dr, rmax));
    return rcpp_result_gen;
END_RCPP
}
// paircountxy
List paircountxy(NumericMatrix x, NumericMatrix y, double dr, double rmax);
RcppExport SEXP _cooltools_paircountxy(SEXP xSEXP, SEXP ySEXP, SEXP drSEXP, SEXP rmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type dr(drSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(paircountxy(x, y, dr, rmax));
    return rcpp_result_gen;
END_RCPP
}
// paircountxx1d
List paircountxx1d(NumericVector x, double dr, double rmax);
RcppExport SEXP _cooltools_paircountxx1d(SEXP xSEXP, SEXP drSEXP, SEXP rmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type dr(drSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(paircountxx1d(x, dr, rmax));
    return rcpp_result_gen;
END_RCPP
}
// paircountxy1d
List paircountxy1d(NumericVector x, NumericVector y, double dr, double rmax);
RcppExport SEXP _cooltools_paircountxy1d(SEXP xSEXP, SEXP ySEXP, SEXP drSEXP, SEXP rmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type dr(drSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(paircountxy1d(x, y, dr, rmax));
    return rcpp_result_gen;
END_RCPP
}
// kde2stampxx
NumericMatrix kde2stampxx(NumericMatrix map, NumericMatrix counts, int hmax, double s, double sdmin, double sdmax, double d, int nkernels, NumericVector kern, NumericVector kernindex, NumericVector kernlength);
RcppExport SEXP _cooltools_kde2stampxx(SEXP mapSEXP, SEXP countsSEXP, SEXP hmaxSEXP, SEXP sSEXP, SEXP sdminSEXP, SEXP sdmaxSEXP, SEXP dSEXP, SEXP nkernelsSEXP, SEXP kernSEXP, SEXP kernindexSEXP, SEXP kernlengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type map(mapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type hmax(hmaxSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type sdmin(sdminSEXP);
    Rcpp::traits::input_parameter< double >::type sdmax(sdmaxSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nkernels(nkernelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kern(kernSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kernindex(kernindexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kernlength(kernlengthSEXP);
    rcpp_result_gen = Rcpp::wrap(kde2stampxx(map, counts, hmax, s, sdmin, sdmax, d, nkernels, kern, kernindex, kernlength));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cooltools_paircountxx", (DL_FUNC) &_cooltools_paircountxx, 3},
    {"_cooltools_paircountxy", (DL_FUNC) &_cooltools_paircountxy, 4},
    {"_cooltools_paircountxx1d", (DL_FUNC) &_cooltools_paircountxx1d, 3},
    {"_cooltools_paircountxy1d", (DL_FUNC) &_cooltools_paircountxy1d, 4},
    {"_cooltools_kde2stampxx", (DL_FUNC) &_cooltools_kde2stampxx, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_cooltools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
