# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

paircountxx <- function(x, dr, rmax) {
    .Call('_cooltools_paircountxx', PACKAGE = 'cooltools', x, dr, rmax)
}

paircountxy <- function(x, y, dr, rmax) {
    .Call('_cooltools_paircountxy', PACKAGE = 'cooltools', x, y, dr, rmax)
}

paircountxx1d <- function(x, dr, rmax) {
    .Call('_cooltools_paircountxx1d', PACKAGE = 'cooltools', x, dr, rmax)
}

paircountxy1d <- function(x, y, dr, rmax) {
    .Call('_cooltools_paircountxy1d', PACKAGE = 'cooltools', x, y, dr, rmax)
}

kde2stampxx <- function(map, counts, hmax, s, sdmin, sdmax, d, nkernels, kern, kernindex, kernlength) {
    .Call('_cooltools_kde2stampxx', PACKAGE = 'cooltools', map, counts, hmax, s, sdmin, sdmax, d, nkernels, kern, kernindex, kernlength)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_cooltools_RcppExport_registerCCallable', PACKAGE = 'cooltools')
})
