# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

paircountxx <- function(x, dr, rmax) {
    .Call('_cooltools_paircountxx', PACKAGE = 'cooltools', x, dr, rmax)
}

paircountxy <- function(x, y, dr, rmax) {
    .Call('_cooltools_paircountxy', PACKAGE = 'cooltools', x, y, dr, rmax)
}

